apiVersion: v1
kind: Service
metadata:
  name: credit-card-data-processor
  namespace: credit-card-data-streaming-101-ns
spec:
  type: LoadBalancer
  selector:
    app: credit-card-data-processor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
