apiVersion: apps/v1
kind: Deployment
metadata:
  name: credit-card-data-processor-streaming-app-v2
  namespace: credit-card-data-streaming-101-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: credit-card-data-processor-streaming-app-v2
  template:
    metadata:
      labels:
        app: credit-card-data-processor-streaming-app-v2
      namespace: credit-card-data-streaming-101-ns
    spec:
      serviceAccountName: credit-card-data-streaming-svc
      containers:
        - name: credit-card-data-processor-v2
          image: asia-south2-docker.pkg.dev/sapient-data-streaming-project/data-streaming-repository/credit-card-data-processor-streaming-app-v2:1.0.0
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "1"
              cpu: "1"
            requests:
              memory: "3"
              cpu: "2"
